FROM nanocurrency/nano-env:base

RUN apt-get update -yqq && apt-get install -yqq git lcov python3-pip
RUN python3 -m pip install cpp_coveralls pyyaml

ENV BOOST_ROOT=/tmp/boost

ADD util/build_prep/fetch_boost.sh fetch_boost.sh

RUN COMPILER=gcc ./fetch_boost.sh
ARG REPOSITORY=nanocurrency/nano-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY