name: Static Analyzers

on: [push, pull_request]

jobs:
  clang_format:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@50fbc62
      - name: Get clang-format 8
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-8 1000
      - name: Clang Format
        run: ci/check-commit-format.sh

  coverage_test:
    name: Coverage Test [TEST_USE_ROCKSDB=${{ matrix.TEST_USE_ROCKSDB }}]
    continue-on-error: true
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        TEST_USE_ROCKSDB:
          - 0
          - 1
    timeout-minutes: 60
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@5a4ac90
        with:
          submodules: "true"
      - name: Fetch Deps
        env:
          COMPILER: gcc
          BOOST_ROOT: /tmp/boost
        run: |
          sudo apt-get update -qq && sudo apt-get install -yqq build-essential g++ wget python zlib1g-dev qt5-default \
          valgrind xorg xvfb xauth xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic ocl-icd-opencl-dev \
          git lcov python3-pip
          COMPILER=gcc util/build_prep/fetch_boost.sh
          wget -O cmake_install.sh https://github.com/Kitware/CMake/releases/download/v3.15.4/cmake-3.15.4-Linux-x86_64.sh && \
          chmod +x cmake_install.sh && \
          sudo ./cmake_install.sh --prefix=/usr --exclude-subdir --skip-license

      - name: Build Run and Test
        env:
          LCOV: 1
          TEST_USE_ROCKSDB: ${{ matrix.TEST_USE_ROCKSDB }}
        run: ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: rocksdb-${{ matrix.TEST_USE_ROCKSDB }}
          parallel: true

  finish:
    needs: coverage_test
    runs-on: ubuntu-18.04
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
